default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contact_development
  username: username
  password: '123456789'
  host: localhost
  port: 5432

test:
  <<: *default
  database: contact_test
  username: username
  password: '123456789'
  host: localhost
  port: 5432

production:
  <<: *default
  database: contact_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>


# PARA HEROKU
# Postgreslq configs
#
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#
# development:
#   <<: *default
#   database: myapp_development
#
# test:
#   <<: *default
#   database: myapp_test
